### ISSUE TITLE
DB cleanup upon each docker start

### ISSUE THREAD

**Issue by daxy01** [xirixiz/dsmr-reader-docker#194]
First of all, I'm a huge fan of your docker images and thanks for taking the time to create them!

I just upgraded to latest-2021.03.05 and noticed the start-up time was many minutes instead of seconds.
Looking further, it seems a DB cleanup is started upon each start as introduced in: https://github.com/xirixiz/dsmr-reader-docker/pull/188

The DB cleanup does a VACUUM on the DB. On one hand I can understand the desire to have a cleaned DB at start-up, downside is the duration of DSMR start-up time.

Has this been a conscious decision to add the cleandb at start, a mistake or is the long duration an unintended result?
Thanks!

**Comment by xirixiz** [comment]
Thanks for the compliment! I've introduced the cleanup at startup due to users more often complain about messages in DSMR complaining about "database polution". Probably, you never ran the cleanup and therefor it was taking a long time :). I think when you recreate the container now, then you probably will not notice any delay. Can you verify this?

However, I can make this optional and enable it by default, that would be better so I`ll add it to the next release.

**Comment by xirixiz** [comment]
I've updated the development branch already, so next release you can choose.

**Comment by daxy01** [comment]
@xirixiz, the startup remained slow even after recreating the container. I guess it could be due to my total DB size as when i manually clean it (in verbose), it tells me it hardly has any removable entries (it does have ~6 million non-removable entries).
I'll try the option when it's moved to the latest branch 😀

Thanks for your super-fast fix!

**Comment by xirixiz** [comment]
By default it's disabled now btw.

**Comment by daxy01** [comment]
Awesome, works like a charm! Thanks!
