### ISSUE TITLE
Protect interface with username/password

### ISSUE THREAD

**Issue by JBS5** [xirixiz/dsmr-reader-docker#34]
The documentation of the origional DSMR-reader tells something about protecting the interface with a username and password: https://dsmr-reader.readthedocs.io/en/latest/application.html#public-webinterface-warning
Any change to do the same with this docker?

**Comment by xirixiz** [comment]
Sure, should be easy. I`ll look into it.

**Comment by jantje88** [comment]
I'm curious if you have already looked into this?

**Comment by JBS5** [comment]
Thanks for your suggestion!
I am using Traefik and added basic auth to the rule file:

```
    [frontends.dsmr.auth.basic]
      removeHeader = true
      users = [
        "XX"
      ]  

```

**Comment by xirixiz** [comment]
The problem is that the creator of dsmr reader isn't that familiar with Docker. Don't get me wrong, he did a great job creating this application, but it's a pain in the ass to use with Docker. Currently I`m looking into his code to see if I can create a pull request to make it more easy to use with Docker.
