### ISSUE TITLE
cpu usage

### ISSUE THREAD

**Issue by Giel538** [xirixiz/dsmr-reader-docker#81]
Not a real problem, and i'm not sure if it can be improved but dsmr reader and database are taking a lot of cpu usage compared to all my other dockers.

This is with DSMR reader
![with](https://user-images.githubusercontent.com/48258564/68075231-5dffff00-fda5-11e9-9740-07adfa7ff3b0.PNG)

This is without
![without](https://user-images.githubusercontent.com/48258564/68075243-7708b000-fda5-11e9-8612-1babf0ff135b.PNG)

**Comment by jorkzijlstra** [comment]
I had the same issue. How long does it take to load the status and statistics page of the dsmr web interface. And how long does it take to do the count on the statistics page

In my case I had a missing index on the database due to some testing in the my first tries.

What exporter are you using for those statistics? I also want them on my environment and these look pretty nice for starters.

**Comment by Giel538** [comment]
Hi,

I'm using glances for the stats. https://nicolargo.github.io/glances/

This screenshots were taken one hour after a new installation. All pages are loading fine. I tried also another docker and had the same results. So i think it is something in the dsmr-reader itself .

**Comment by jorkzijlstra** [comment]
I have added some metrics to my environment by booting up some additional docker containers (prometheus, grafana, cAdvisor, node-exporter) to get some of the same insights.

It seem that indeed the dsmr softare is quite cpu heavy.
![image](https://user-images.githubusercontent.com/15804835/68092128-42215980-fe88-11e9-9e97-bb866fa21ab8.png)

I don't think the issue here is the docker container but rather the software which need some more investigation.

**Comment by xirixiz** [comment]
Wellicht dat dit kan helpen: 
https://github.com/dennissiemensma/dsmr-reader/issues/600
https://github.com/dennissiemensma/dsmr-reader/issues/413

Ik heb die settings een tijd geleden instelbaar gemaakt voor de Docker image.
