### ISSUE TITLE
Datalogger cannot be disabled (when using API)

### ISSUE THREAD

**Issue by DiedB** [xirixiz/dsmr-reader-docker#97]
I am using a Raspberry Pi as datalogger locally, which only uses the API on my server (which runs this container). Since upgrading to v3.3, CPU usage on my server rised to 100%, caused by the `supervisord` service and the `datalogger` Python script within the container. The datalogger is not used in the Docker container, but can't be disabled. 

The issue was that my COM device port was not mapped through to Docker causing something in the logger to hang or keep looping. However, I would like to disable it entirely to prevent future issues, and would prefer not adding an unused device mapping here.

The docker container at https://hub.docker.com/r/ualex73/dsmr-reader-docker/ supports three modes (one of which is `SERVER_NO_DATALOGGER`), could these also be supported here?

**Comment by DiedB** [comment]
See https://github.com/dennissiemensma/dsmr-reader/issues/879 for more information.

**Comment by DiedB** [comment]
Any response?

**Comment by xirixiz** [comment]
Have you read the solution in the link you posted? Modify the env var to disable the datalogger on startup of the docker container. Isn’t that the solution you were looking for? The datalogger can’t be disabled via the api because docker starts the process via supervisord, which isn’t used in a regular installation. It’s up to the developer to modify the source code to support disabling the datalogger via the api.

Hope this answers your question ✌🏻

**Comment by DiedB** [comment]
Thanks, must have been asleep when reading that one!
